inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 80

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/FormatStringToken:
  EnforcedStyle: unannotated
